spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=VOTACAO
spring.datasource.password=Votacao#123

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
debug=true

springdoc.swagger-ui.path=/swagger-ui.html

api.security.token.security=MINHA_PALAVRA_SECRETA

springdoc.swagger-ui.persistAuthorization=true
springdoc.swagger-ui.doc-expansion=none

ibge.base-url=https://servicodados.ibge.gov.br/api/v1/localidades

viacep.base-url=https://viacep.com.br

logging.level.org.springframework.security=DEBUG





